version: '3.9'

x-vol-args: &args
  volumes: 
    - ./.material:/app/.material

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: super-secret-password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - dev-data:/var/lib/postgresql/data
    
  gutenberg:
    image: gutenberg-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args: 
        CACHE_BUST: ${CACHE_BUST}
        MATERIAL_METHOD: "pull"
        MATERIAL_DIR: ".material"
        YAML_TEMPLATE: "config/oxford.yaml"
    command: "yarn dev"
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
    ports:
      - "3000:3000"
    links: 
      - db
    <<: *args
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:super-secret-password@db:5432
volumes:
  dev-data:
