x-vol-args: &args
  volumes: 
    - ./.material:/app/.material

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: super-secret-password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - dev-data:/var/lib/postgresql/data
    
  gutenberg:
    image: gutenberg-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args: 
        CACHE_BUST: ${CACHE_BUST}
        MATERIAL_METHOD: "pull"
        MATERIAL_DIR: ".material"
        YAML_TEMPLATE: "config/oxford.yaml"
    command: "yarn dev"
    volumes:
      - node-modules:/app/node_modules
      - ./.material:/app/.material
      - ./config:/app/config
      - ./components:/app/components
      - ./lib:/app/lib
      - ./pages:/app/pages
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./styles:/app/styles
      - ./.env:/app/.env
      - ./next.config.js:/app/next.config.js
      - ./cypress.config.ts:/app/cypress.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
    ports:
      - "3000:3000"
    links: 
      - db
    <<: *args
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:super-secret-password@db:5432
volumes:
  dev-data:
  node-modules:
