-- AlterTable
ALTER TABLE "EventGroup" ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "summary" SET DEFAULT '',
ALTER COLUMN "start" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "end" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "location" SET DEFAULT '';

-- AlterTable
ALTER TABLE "EventItem" ALTER COLUMN "order" SET DEFAULT 0,
ALTER COLUMN "section" SET DEFAULT '';
