-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "summary" SET DEFAULT '',
ALTER COLUMN "start" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "end" SET DEFAULT CURRENT_TIMESTAMP;
